brew "direnv"
brew "fzf"
brew "gh"
brew "git-delta"
brew "mise"
brew "neovim"
brew "rcm"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "ghostty"
