source ~/.zsh/env.sh
source ~/.zsh/path.sh
source ~/.zsh/ruby.sh
source ~/.zsh/prompt.sh
source ~/.zsh/aliases.sh
source ~/.zsh/functions.sh
source ~/.zsh/completions.sh
source ~/.zsh/coffee.sh
source ~/.zsh/android.sh
source ~/.zsh/z.sh
source ~/.zsh/python.sh
source ~/.zsh/xcode.sh
