#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Klaas Pieter Annema"
email = "kp@annema.me"

[signing]
behavior = "drop"
backend = "ssh"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFqt7Xr7Ue/lvzaJ8pB011Fk2oGUzZDWxoAu35+ZfeMd"

[ui]
show-cryptographic-signatures = true

[git]
sign-on-push = true
