tap "caskroom/cask"
tap "klaaspieter/formula"
tap "thoughtbot/formulae"

# Unix
brew "autojump"
brew "git"
brew "gnupg"
brew "neovim"
brew "openssl"
brew "pass"
brew "rcm"
brew "reattach-to-user-namespace"
brew "shellcheck"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "xcrecord"
brew "zsh"

# GitHub
brew "hub"

# Image manipulation
brew "imagemagick"

# Programming language prerequisites and package managers
brew "autoconf"
brew "coreutils"
brew "libyaml" # should come after openssl

# Mac
brew "trash"

# Databases
brew "postgres", restart_service: :changed
brew "redis", restart_service: :changed

# Xcode
brew "carthage"
brew "swiftlint"
brew "xcode-cli"
tap "gfontenot/formulae"

# Fonts
tap "caskroom/fonts"
cask "font-hack"

# Apps
cask "alfred"
cask "arq"
cask "bartender"
cask "caffeine"
cask "dash"
cask "delta"
cask "divvy"
cask "dropbox"
cask "expressvpn"
cask "firefox"
cask "istat-menus"
cask "iterm2"
cask "omnifocus"
cask "sketch"
cask "slack"
cask "spotify"
cask "steam"
cask "transmission"
cask "whatsapp"
cask "wkhtmltopdf"
cask "zoomus"

# Mac App Store
mas "Letters", id: 1196993429
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
